/**
 * MIKAGE — /critic/vision_critic.js
 * Layer 2 — AI vision critic. Detects 3 specific issues only.
 *
 * Detections:
 *   1. Plastic/synthetic look
 *   2. Lack of depth (foreground/background separation)
 *   3. Over-polish (too clean, too perfect)
 *
 * In production, reads a live judge payload generated by the render worker.
 * If that payload is missing, this module must return UNAVAILABLE.
 *
 * No simulated pass/fail is allowed in the active path.
 */

"use strict";

// ===================================================================
// THRESHOLDS
// ===================================================================

const THRESHOLDS = Object.freeze({
  plastic_max: 0.35,       // confidence above this = plastic detected
  depth_lack_max: 0.40,    // confidence above this = depth missing
  overpolish_max: 0.35,    // confidence above this = over-polished
});

// ===================================================================
// TASK-ALIGNED PROMPT — sent to VLM in production
// ===================================================================

const VLM_SYSTEM_PROMPT = Object.freeze(
  "You are a technical image quality inspector for a hard sci-fi porcelain " +
  "armor character project. You do NOT evaluate subjective beauty. You report " +
  "structural issues only.\n\n" +
  "Analyze the provided image for exactly 3 criteria. For each, return a " +
  "confidence score from 0.0 (not detected) to 1.0 (strongly detected).\n\n" +
  "1. PLASTIC_LOOK: Are surfaces unnaturally smooth, waxy, or synthetic? " +
  "Does skin or armor read as molded plastic rather than matte ceramic? " +
  "Check for uniform surface finish lacking micro-detail.\n\n" +
  "2. LACK_OF_DEPTH: Is foreground-background separation weak? Are layers " +
  "visually flat? Is there no atmospheric perspective, no depth-of-field " +
  "gradient, no foreground element creating dimensionality?\n\n" +
  "3. OVER_POLISH: Is the image too clean, too perfect, too uniform? " +
  "Are there no imperfections, no wear marks, no micro-cracks, no " +
  "asymmetries? Does it read as digitally perfect rather than physically real?\n\n" +
  "RESPOND ONLY with a JSON object:\n" +
  '{"plastic_look": 0.0, "lack_of_depth": 0.0, "over_polish": 0.0}'
);

function buildUnavailableVisionResult() {
  return {
    mode: "unavailable",
    source: "unavailable",
    status: "UNAVAILABLE",
    vision_score: null,
    quality_score: null,
    failure_codes: [],
    issues: ["LIVE_JUDGE_UNAVAILABLE"],
    verdict: "UNAVAILABLE",
    raw: null,
  };
}

function normalizeVerdict(status, score) {
  if (status === "PASS") return "PASS";
  if (status === "REVIEW") return "REVIEW";
  if (status === "REJECT" || status === "FAIL") return "REJECT";
  if (typeof score === "number") {
    if (score >= 0.75) return "PASS";
    if (score >= 0.6) return "REVIEW";
    return "REJECT";
  }
  return "UNAVAILABLE";
}

async function runVisionCritic(input = {}) {
  const liveJudgeOutput = input.liveJudgeOutput || null;
  if (!liveJudgeOutput || String(liveJudgeOutput.source || "").toLowerCase() !== "live") {
    return buildUnavailableVisionResult();
  }

  const qualityScore = typeof liveJudgeOutput.quality_score === "number"
    ? liveJudgeOutput.quality_score
    : typeof liveJudgeOutput.overall_score === "number"
      ? liveJudgeOutput.overall_score
      : null;
  const issues = []
    .concat(liveJudgeOutput.failure_codes || [])
    .concat(liveJudgeOutput.notes || [])
    .filter(Boolean)
    .map((value) => String(value));

  return {
    mode: "gemini_live",
    source: "live",
    status: "LIVE",
    vision_score: qualityScore,
    quality_score: qualityScore,
    failure_codes: (liveJudgeOutput.failure_codes || []).map((value) => String(value)),
    issues,
    verdict: normalizeVerdict(String(liveJudgeOutput.status || "").toUpperCase(), qualityScore),
    raw: liveJudgeOutput,
  };
}

// ===================================================================
// EXPORTS
// ===================================================================

module.exports = {
  runVisionCritic,
  buildUnavailableVisionResult,
  THRESHOLDS,
  VLM_SYSTEM_PROMPT,
};
