"use strict";

const path = require("path");
const { resolveMachineProfile } = require("./machine_profile");
const { resolveNodeRole } = require("../node_role");

const ROOT = path.resolve(__dirname, "..", "..");
const BRIDGE_ROOT = path.join(ROOT, "control_plane", "commander_bridge");
const MACHINE_PROFILE = resolveMachineProfile({ hostname: process.env.COMPUTERNAME || process.env.HOSTNAME });
const NODE_ROLE = resolveNodeRole(MACHINE_PROFILE);

module.exports = {
  ROOT,
  BRIDGE_ROOT,
  MACHINE_PROFILE,
  NODE_ROLE,
  TASKS_DIR: path.join(ROOT, "tasks"),
  CONTROL_API_HOST: process.env.MIKAGE_CONTROL_API_HOST || "127.0.0.1",
  CONTROL_API_PORT: Number(process.env.MIKAGE_CONTROL_API_PORT || 3032),
  INBOX_DIR: path.join(BRIDGE_ROOT, "inbox"),
  OUTBOX_DIR: path.join(BRIDGE_ROOT, "outbox"),
  STATE_DIR: path.join(BRIDGE_ROOT, "state"),
  LOGS_DIR: path.join(BRIDGE_ROOT, "logs"),
  ARCHIVE_DIR: path.join(BRIDGE_ROOT, "archive"),
  AUDIT_LOG: path.join(BRIDGE_ROOT, "logs", "audit.log"),
  LATEST_AGENT_REPORT: path.join(BRIDGE_ROOT, "state", "latest_agent_report.json"),
  PENDING_ACTIONS: path.join(BRIDGE_ROOT, "state", "pending_actions.json"),
  SYSTEM_RUNTIME_SNAPSHOT: path.join(BRIDGE_ROOT, "state", "system_runtime_snapshot.json"),
  LOCAL_AGENT_STATE_DIR: path.join(ROOT, "control_plane", "local_control_agent", "state"),
  LOCAL_AGENT_REPORTS_DIR: path.join(ROOT, "control_plane", "local_control_agent", "state", "reports"),
  LOCAL_AGENT_LAST_ACTION: path.join(ROOT, "control_plane", "local_control_agent", "state", "latest_reviewed_action.json"),
  LOCAL_AGENT_LAST_DESKTOP_ACTION: path.join(ROOT, "control_plane", "local_control_agent", "state", "latest_desktop_action.json"),
  LOCAL_AGENT_LAST_OBSERVER_ACTION: path.join(ROOT, "control_plane", "local_control_agent", "state", "latest_desktop_observer_action.json"),
  USER_SESSION_STATE: path.join(BRIDGE_ROOT, "state", "user_session.json"),
  AGENT_SESSION_STATE: path.join(BRIDGE_ROOT, "state", "agent_session.json"),
  WORKFLOW_REGISTRY_JSON: path.join(BRIDGE_ROOT, "state", "workflow_run_registry.json"),
  WORKFLOW_REGISTRY_JSONL: path.join(BRIDGE_ROOT, "state", "workflow_run_history.jsonl"),
  APPROVAL_QUEUE_PATH: path.join(BRIDGE_ROOT, "state", "approval_queue.json"),
  APPROVAL_QUEUE_HISTORY_JSONL: path.join(BRIDGE_ROOT, "state", "approval_queue_history.jsonl"),
  APPROVAL_INBOX_PATH: path.join(BRIDGE_ROOT, "state", "approval_inbox.json"),
  APPROVAL_INBOX_HISTORY_JSONL: path.join(BRIDGE_ROOT, "state", "approval_inbox_history.jsonl"),
  ACTION_PREVIEW_DIR: path.join(BRIDGE_ROOT, "state", "action_previews"),
  DIFF_PREVIEW_DIR: path.join(BRIDGE_ROOT, "state", "diff_previews"),
  TASK_CONTRACT_DIR: path.join(BRIDGE_ROOT, "state", "task_contracts"),
  TASK_BRIEF_DIR: path.join(BRIDGE_ROOT, "state", "task_briefs"),
  CODEX_DISPATCH_PACK_DIR: path.join(BRIDGE_ROOT, "state", "codex_dispatch_packs"),
  EXECUTOR_JOB_DIR: path.join(BRIDGE_ROOT, "state", "executor_jobs"),
  EXECUTOR_JOB_REGISTRY_PATH: path.join(BRIDGE_ROOT, "state", "executor_job_registry.json"),
  EXECUTOR_JOB_HISTORY_JSONL: path.join(BRIDGE_ROOT, "state", "executor_job_history.jsonl"),
  EXECUTION_RESULT_DIR: path.join(BRIDGE_ROOT, "state", "execution_results"),
  EXECUTION_FAILURE_DIR: path.join(BRIDGE_ROOT, "state", "execution_failures"),
  RESULT_INGEST_DIR: path.join(BRIDGE_ROOT, "state", "result_ingest"),
  EXECUTION_REPORT_DIR: path.join(BRIDGE_ROOT, "state", "execution_reports"),
  EXECUTOR_STATUS_TRACKER_PATH: path.join(BRIDGE_ROOT, "state", "executor_status_tracker.json"),
  PERSISTENT_TASK_QUEUE_PATH: path.join(BRIDGE_ROOT, "state", "persistent_task_queue.json"),
  PERSISTENT_TASK_QUEUE_HISTORY_JSONL: path.join(BRIDGE_ROOT, "state", "persistent_task_queue_history.jsonl"),
  EXECUTION_RESUME_STATE_PATH: path.join(BRIDGE_ROOT, "state", "execution_resume_state.json"),
  BOUNDED_RETRY_STATE_PATH: path.join(BRIDGE_ROOT, "state", "bounded_retry_state.json"),
  SPAWN_REGISTRY_PATH: path.join(BRIDGE_ROOT, "state", "spawn_registry.json"),
  SPAWN_REGISTRY_HISTORY_JSONL: path.join(BRIDGE_ROOT, "state", "spawn_registry_history.jsonl"),
  PROCESS_INCIDENT_REGISTRY_PATH: path.join(BRIDGE_ROOT, "state", "process_incidents.json"),
  PROCESS_INCIDENT_HISTORY_JSONL: path.join(BRIDGE_ROOT, "state", "process_incidents_history.jsonl"),
  WATCHDOG_ACTION_DIR: path.join(BRIDGE_ROOT, "state", "watchdog_actions"),
  SINGLETON_LOCKS_PATH: path.join(BRIDGE_ROOT, "state", "singleton_locks.json"),
  SPAWN_RATE_LIMITER_PATH: path.join(BRIDGE_ROOT, "state", "spawn_rate_limiter.json"),
  PROCESS_GOVERNOR_STATE_PATH: path.join(BRIDGE_ROOT, "state", "process_governor_state.json"),
  GOAL_STATE_REGISTRY_PATH: path.join(BRIDGE_ROOT, "state", "goal_state_registry.json"),
  PROGRESS_EVAL_DIR: path.join(BRIDGE_ROOT, "state", "progress_evals"),
  NEXT_TASK_CANDIDATES_DIR: path.join(BRIDGE_ROOT, "state", "next_task_candidates"),
  NEXT_TASK_DECISION_DIR: path.join(BRIDGE_ROOT, "state", "next_task_decisions"),
  AUTONOMY_BUDGET_STATE_PATH: path.join(BRIDGE_ROOT, "state", "autonomy_budget_state.json"),
  REPO_HEALTH_SCAN_DIR: path.join(BRIDGE_ROOT, "state", "repo_health_scans"),
  MAINTENANCE_ISSUE_REGISTRY_PATH: path.join(BRIDGE_ROOT, "state", "maintenance_issue_registry.json"),
  SELF_HEAL_CANDIDATES_DIR: path.join(BRIDGE_ROOT, "state", "self_heal_candidates"),
  SELF_HEAL_DECISION_DIR: path.join(BRIDGE_ROOT, "state", "self_heal_decisions"),
  MAINTENANCE_BUDGET_STATE_PATH: path.join(BRIDGE_ROOT, "state", "maintenance_budget_state.json"),
  LIVE_OPERATION_PROOF_DIR: path.join(BRIDGE_ROOT, "state", "live_operation_proofs"),
  STABILITY_ANOMALY_REGISTRY_PATH: path.join(BRIDGE_ROOT, "state", "stability_anomaly_registry.json"),
  STABILITY_ANOMALY_HISTORY_JSONL: path.join(BRIDGE_ROOT, "state", "stability_anomaly_history.jsonl"),
  OPERATOR_FRICTION_REPORT_DIR: path.join(BRIDGE_ROOT, "state", "operator_friction_reports"),
  FAILURE_CENTER_PATH: path.join(BRIDGE_ROOT, "state", "failure_center.json"),
  FAILURE_CENTER_HISTORY_JSONL: path.join(BRIDGE_ROOT, "state", "failure_center_history.jsonl"),
  RETRY_QUEUE_PATH: path.join(BRIDGE_ROOT, "state", "retry_queue.json"),
  RETRY_QUEUE_HISTORY_JSONL: path.join(BRIDGE_ROOT, "state", "retry_queue_history.jsonl"),
  TASK_LIFECYCLE_DIR: path.join(BRIDGE_ROOT, "state", "task_lifecycle"),
  GOVERNANCE_REPORTS_PATH: path.join(BRIDGE_ROOT, "state", "governance_reports.json"),
  GOVERNANCE_REPORTS_HISTORY_JSONL: path.join(BRIDGE_ROOT, "state", "governance_reports_history.jsonl"),
  OPERATOR_ACTIVITY_FEED_PATH: path.join(BRIDGE_ROOT, "state", "operator_activity_feed.json"),
  OPERATOR_ACTIVITY_FEED_HISTORY_JSONL: path.join(BRIDGE_ROOT, "state", "operator_activity_feed_history.jsonl"),
  AUDIT_TRAIL_PATH: path.join(BRIDGE_ROOT, "state", "audit_trail.json"),
  AUDIT_TRAIL_HISTORY_JSONL: path.join(BRIDGE_ROOT, "state", "audit_trail_history.jsonl"),
  WORKFLOW_SUMMARY_PATH: path.join(BRIDGE_ROOT, "state", "workflow_summaries.json"),
  INTENT_REGISTRY_PATH: path.join(BRIDGE_ROOT, "state", "intent_registry.json"),
  INTENT_HISTORY_JSONL: path.join(BRIDGE_ROOT, "state", "intent_history.jsonl"),
  AUTO_TASK_REGISTRY_PATH: path.join(BRIDGE_ROOT, "state", "auto_task_registry.json"),
  AUTO_TASK_HISTORY_JSONL: path.join(BRIDGE_ROOT, "state", "auto_task_history.jsonl"),
  LOOP_GUARD_STATE_PATH: path.join(BRIDGE_ROOT, "state", "loop_guard_state.json"),
  GOVERNANCE_SNAPSHOT_LATEST: path.join(BRIDGE_ROOT, "state", "governance_snapshot_latest.json"),
  GOVERNANCE_SNAPSHOT_HISTORY_JSONL: path.join(BRIDGE_ROOT, "state", "governance_snapshot_history.jsonl"),
  OPERATOR_REPORTS_JSONL: path.join(BRIDGE_ROOT, "state", "operator_reports.jsonl"),
  REPORT_DEDUPE_CACHE_PATH: path.join(BRIDGE_ROOT, "state", "report_dedupe_cache.json"),
  APPROVAL_POLICY: path.join(BRIDGE_ROOT, "approval_policy.json"),
  APPROVAL_MODEL: path.join(ROOT, "control_plane", "approval_model.json"),
  ENTRYPOINTS_REGISTRY: path.join(ROOT, "state", "system_entrypoints.json"),
  STORAGE_POLICY_LOCK: path.join(ROOT, "STORAGE_POLICY_LOCK.md"),
  SAFE_CLEAN_GLOBS: ["__pycache__", ".pytest_cache", ".cache", "Thumbs.db"],
  SAFE_CLEAN_EXTENSIONS: [".log", ".tmp", ".temp", ".cache"],
  PROCESS_LIMITS: {
    max_launches_per_minute: 12,
    max_concurrent_children: 4,
    failure_cooldown_ms: 120000,
    max_visible_cmd_launches_per_minute: 2,
    default_timeout_ms: 30000,
    crash_loop_threshold: 3,
    stale_running_ms: 300000,
  },
  PROTECTED_PATH_PREFIXES: [
    ROOT.toLowerCase(),
    "g:\\my drive".toLowerCase(),
    "c:\\users\\this pc\\desktop".toLowerCase(),
    "c:\\users\\this pc\\documents".toLowerCase(),
    "c:\\users\\this pc\\downloads".toLowerCase(),
    "c:\\users\\this pc\\pictures".toLowerCase(),
    "c:\\users\\this pc\\videos".toLowerCase()
  ],
  ARCH_SENSITIVE_PATHS: [
    "start_mikage.bat",
    "MIKAGE/index.js",
    "runtime/drive_queue/runtime.js",
    "runtime/colab_worker/",
    "control_plane/",
    "state/system_entrypoints.json"
  ],
  ALLOWED_WRITE_PREFIXES: [
    path.join(ROOT, "control_plane", "commander_bridge").toLowerCase(),
    path.join(ROOT, "control_plane", "local_control_agent").toLowerCase(),
    path.join(ROOT, "state").toLowerCase(),
    path.join(ROOT, "tests").toLowerCase()
  ]
};
