#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
mikage_render_gate_fal.py — V0.1

Mikage Zenith repo render gate for FAL image generation.

Reads a prompt_pack/v0.1 JSON brief sidecar, enforces hard render gates,
converts the long brief prompt into a compact render prompt, optionally
calls FAL, writes a structured run folder and attempt reports.

Hard gates (any one of these blocks the API call):
  - project_metadata.operator_approval_token is null  -> RENDER_BLOCKED_OPERATOR_APPROVAL_REQUIRED
  - config.model_id == "CHUA_XAC_NHAN"                -> FAL_MODEL_ID_CHUA_XAC_NHAN
  - env var FAL_KEY / FAL_API_KEY missing             -> FAL_API_KEY_MISSING
  - CLI flag --dry-run                                -> DRY_RUN_PASS_NO_API_CALL

This tool MUST NOT:
  - modify the source brief JSON
  - mark any output PASS for visual quality
  - establish anchor_lyre_001 or any other anchor
  - edit any canon file
  - asset-lock any output
  - promote anything from PROPOSAL to canon

Operator-only steps are documented in the config file and the V0.1 README.

Usage:
    python tools/render_gate/mikage_render_gate_fal.py \
        --brief docs/automation/render_briefs/BRIEF_COMMANDER_LYRE_PHASE_1_IMPERIAL_DUTY_V0_1.json
    python tools/render_gate/mikage_render_gate_fal.py \
        --brief <brief.json> --dry-run
    python tools/render_gate/mikage_render_gate_fal.py \
        --brief <brief.json> --config tools/render_gate/mikage_render_gate_config.json

Exit codes:
    0  = clean exit on any V0.1 status (including blocked / dry-run / API-failure)
         The tool never raises on a normal gate trigger; it writes a report and exits 0.
    2  = CLI usage error or unreadable inputs (failed before the gate logic ran)

Generated by: Claude Cowork (Mikage repo operator)
Generated on: 2026-05-31
Status: DRAFT_PROPOSAL_NOT_CANON
"""

from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import os
import sys
import traceback
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

# -----------------------------------------------------------------------------
# Constants
# -----------------------------------------------------------------------------

TOOL_NAME = "mikage_render_gate_fal"
TOOL_VERSION = "0.1"
SCHEMA_EXPECTED = "prompt_pack/v0.1"

STATUS_BLOCKED_APPROVAL = "RENDER_BLOCKED_OPERATOR_APPROVAL_REQUIRED"
STATUS_FAL_KEY_MISSING = "FAL_API_KEY_MISSING"
STATUS_MODEL_CHUA_XAC_NHAN = "FAL_MODEL_ID_CHUA_XAC_NHAN"
STATUS_API_REQUEST_FAILED = "FAL_API_REQUEST_FAILED"
STATUS_RENDER_OK = "RENDER_OUTPUT_CREATED_VERIFY_NOT_STARTED"
STATUS_DRY_RUN = "DRY_RUN_PASS_NO_API_CALL"

ALL_STATUSES = {
    STATUS_BLOCKED_APPROVAL,
    STATUS_FAL_KEY_MISSING,
    STATUS_MODEL_CHUA_XAC_NHAN,
    STATUS_API_REQUEST_FAILED,
    STATUS_RENDER_OK,
    STATUS_DRY_RUN,
}

# -----------------------------------------------------------------------------
# Compact prompts (V0.1) — deliberate, deterministic, NOT generated from sidecar
# -----------------------------------------------------------------------------

COMPACT_PROMPT_V0_1_COMMANDER_LYRE_PHASE_1 = (
    "Cinematic 2.35:1 key visual. A tall sealed androgynous imperial enforcement figure "
    "stands perfectly still at the center of a monumental sterile white-and-black monolith chamber.\n"
    "The figure is not a heroine, not a soldier pin-up, not a human wearing armor. It reads as "
    "a cold command system given physical form.\n"
    "Body shape: straight vertical silhouette, narrow but not sensual, no breast emphasis, "
    "no hourglass waist, no hip or thigh focus. Heavy sealed ceramic armor plates, slabbed and "
    "industrial, over black graphene underlayer.\n"
    "Helmet: fully sealed smooth white industrial helmet, no face, no mouth, no nose, no eyes, "
    "only one ultra-thin horizontal cyan visor slit.\n"
    "Pose: both hands clasped strictly behind the back. Upright, symmetrical, disciplined, motionless.\n"
    "Left forearm: only a small flat dormant white ceramic disc emitter, folded against the "
    "forearm, about 15cm wide. Not a shield in use. No plasma, no barrier, no glowing dome.\n"
    "Right hip: one slim black cylindrical monowire hilt, holstered. No blade visible.\n"
    "Environment: vast Imperial Spire interior, ghost-white monolith plates, matte black void "
    "gaps, polished black reflective floor, cold overhead interrogation light, hard rim light "
    "from behind, silent severe atmosphere.\n"
    "Material: brushed white ceramic composite, low gloss, micro-grain, industrial precision. "
    "Cyan accent only. No purple. No red. No gold."
)

COMPACT_NEGATIVE_V0_1 = (
    "female body emphasis, sexy armor, breasts, cleavage, hourglass waist, wide hips, "
    "thigh focus, bodysuit, swimsuit armor, pin-up pose, fashion pose, contrapposto, "
    "action pose, hands forward, holding shield, large shield, active shield, plasma shield, "
    "energy dome, glowing barrier, sword, blade, hair, visible face, eyes, mouth, nose, lips, "
    "human skin, porcelain doll face, anime girl, gacha character, cosplay, glossy plastic, "
    "chrome, latex, mecha clutter, gundam, fantasy armor, samurai armor, cape, robe, crown, "
    "halo, purple light, red light, gold trim, text, UI, logo, watermark"
)

# -----------------------------------------------------------------------------
# V0.2 compact prompts — PATH_A revision after attempt_004 verification failed
# 6 of 10 checks (F1/F2/F3/SHIELD/MONOWIRE/ANCHOR). Diagnostic root cause:
# flux/dev model bias dominant — negation alone did not override model defaults.
# V0.2 strategy: front-load POSITIVE shape cues (silhouette / helmet / pose /
# shield / weapon / material / anti-mecha) before any narrative language, and
# strengthen the negative list with the specific failure modes observed.
# -----------------------------------------------------------------------------

COMPACT_PROMPT_V0_2_COMMANDER_LYRE_PHASE_1 = (
    "Genderless industrial command figure. Straight vertical column body. Flat rectangular "
    "chest plate. No chest contour. No waist taper. No hip flare. No thigh emphasis. Slab "
    "ceramic armor plates over black graphene underlayer.\n"
    "Fully sealed smooth white industrial helmet. No face geometry. No eye points. No amber "
    "glow. No facial muscles. Only one ultra-thin horizontal cyan visor slit edge-to-edge "
    "across where eyes would be.\n"
    "Both hands clasped strictly behind the back. No weapon in hands. Motionless symmetrical "
    "command stance. Upright vertical axis. No action pose. No contrapposto.\n"
    "Left forearm: one small flat white ceramic circular disc emitter, approximately 15cm "
    "diameter, folded dormant flat against the forearm, recessed Empire sigil etched in thin "
    "cold-cyan lines. No plasma. No barrier field. No glowing dome. No kite-shape shield.\n"
    "Right hip: one slim black cylindrical monowire hilt, holstered against the hip. No blade "
    "visible. No pistol. No gun. No firearm silhouette in either hand.\n"
    "Material: brushed B4C ceramic surface. Matte low-specular white ceramic plates. Subtle "
    "micro-grain. Shallow subsurface scattering. Not glossy plastic. Not vinyl. Not action "
    "figure finish.\n"
    "Armor construction: clean medical-industrial slab armor. Minimal recessed seams only. No "
    "gundam panels. No decorative greebles. No knee lights. No orange accents. No amber accents.\n"
    "Environment: vast Imperial Spire interior. Ghost-white monolith plates. Matte black void "
    "gaps. Polished black reflective floor. Cold overhead interrogation key light. Hard rim "
    "light from behind. Silent severe atmosphere. Cyan accent only. No purple. No red. No gold. "
    "No warm light anywhere.\n"
    "Composition: cinematic 2.35:1 anamorphic. Centered frontal three-quarter. Vertical axis "
    "through figure. Monumental architectural scale. Premium quiet luxury rendering."
)

COMPACT_NEGATIVE_V0_2 = (
    "female body emphasis, sexy armor, breasts, chest cups, cleavage, hourglass waist, "
    "waist taper, wide hips, hip flare, thigh focus, thigh emphasis, slim curvy body, "
    "android girl, bodysuit, swimsuit armor, pin-up pose, fashion pose, contrapposto, "
    "action pose, hands forward, hands at sides, holding weapon, holding shield, holding pistol, "
    "holding gun, firearm, pistol silhouette, gun in hand, large shield, active shield, "
    "plasma shield, energy dome, glowing barrier, kite-shape shield, sword, blade, hair, "
    "visible face, eye points, glowing eyes, amber eyes, orange eyes, mouth, nose, lips, "
    "human skin, porcelain doll face, chin transition, anime girl, gacha character, cosplay, "
    "glossy plastic, action figure finish, vinyl, chrome, latex, mecha clutter, gundam panels, "
    "decorative greebles, knee lights, orange accent, amber accent, gold trim, hero gold, "
    "fantasy armor, samurai armor, cape, robe, crown, halo, purple light, violet glitch, "
    "red light, crimson, text, UI, logo, watermark"
)


def select_compact_prompt(brief_id: str) -> tuple:
    """
    Route brief_id -> (compact_prompt, compact_negative, prompt_mode_label).

    V0.1 path is preserved unchanged. V0.2 brief_id triggers the redesigned
    front-loaded-positive compact prompt + strengthened negative.

    Unknown brief_ids fall back to V0.1 (legacy default).
    """
    if brief_id == "BRIEF_COMMANDER_LYRE_PHASE_1_IMPERIAL_DUTY_V0_2":
        return (
            COMPACT_PROMPT_V0_2_COMMANDER_LYRE_PHASE_1,
            COMPACT_NEGATIVE_V0_2,
            "compact_prompt_v0_2_lyre_p1",
        )
    return (
        COMPACT_PROMPT_V0_1_COMMANDER_LYRE_PHASE_1,
        COMPACT_NEGATIVE_V0_1,
        "compact_prompt_v0_1",
    )


# -----------------------------------------------------------------------------
# Utility
# -----------------------------------------------------------------------------

def _now_iso() -> str:
    return _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")


def _repo_root_from(brief_path: Path) -> Path:
    """
    Walk up from the brief path until we find the repo root marker.
    We use the presence of `docs/handoff/00_LATEST_CODEX_HANDOFF.md` as the marker
    (every repo state we care about contains it). Falls back to brief_path.parents[3]
    which matches docs/automation/render_briefs/*.json layout.
    """
    p = brief_path.resolve()
    for parent in [p] + list(p.parents):
        candidate = parent / "docs" / "handoff" / "00_LATEST_CODEX_HANDOFF.md"
        if candidate.exists():
            return parent
    # Fallback: assume layout docs/automation/render_briefs/<brief>.json
    try:
        return p.parents[3]
    except IndexError:
        return p.parent


def _sha256_of_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _aspect_ratio_to_size(aspect_ratio: str, resolution_target_px: Optional[str]) -> Tuple[int, int]:
    """
    Convert brief aspect_ratio + optional resolution_target_px into (width, height).
    Deterministic fallbacks if resolution_target_px is malformed or None.
    """
    if resolution_target_px and "x" in resolution_target_px:
        try:
            w_str, h_str = resolution_target_px.lower().split("x", 1)
            w = int("".join(ch for ch in w_str if ch.isdigit()))
            h = int("".join(ch for ch in h_str if ch.isdigit()))
            if w > 0 and h > 0:
                return w, h
        except (ValueError, AttributeError):
            pass
    # Fallback by aspect_ratio
    table = {
        "2.35:1": (2352, 1000),
        "16:9": (1920, 1080),
        "9:16": (1080, 1920),
        "1:1": (1024, 1024),
        "4:5": (1024, 1280),
        "3:4": (960, 1280),
        "4:3": (1280, 960),
        "2.76:1": (2208, 800),
    }
    return table.get(aspect_ratio, (1024, 1024))


# -----------------------------------------------------------------------------
# Config + brief loaders
# -----------------------------------------------------------------------------

def load_config(config_path: Path) -> Dict[str, Any]:
    with config_path.open("r", encoding="utf-8") as f:
        cfg = json.load(f)
    # Defaults
    cfg.setdefault("provider", "fal")
    cfg.setdefault("model_id", "CHUA_XAC_NHAN")
    cfg.setdefault("output_root", "docs/automation/render_briefs/runs")
    cfg.setdefault("default_attempt_count", 1)
    cfg.setdefault("dry_run_default", True)
    cfg.setdefault("fal_endpoint_template", "https://fal.run/{model_id}")
    cfg.setdefault("fal_timeout_seconds", 120)
    cfg.setdefault("fal_request_user_agent", f"{TOOL_NAME}/{TOOL_VERSION}")
    cfg.setdefault("compact_prompt_mode", "compact_prompt_v0_1")
    return cfg


def load_brief(brief_path: Path) -> Dict[str, Any]:
    with brief_path.open("r", encoding="utf-8") as f:
        return json.load(f)


def extract_brief_fields(brief: Dict[str, Any]) -> Dict[str, Any]:
    """
    Pull the required fields out of the brief. Missing fields are recorded
    so the report can flag them, but missing required-for-render fields will
    still cause the gate to refuse to call FAL (we record and continue, not raise).
    """
    pm = brief.get("project_metadata", {}) or {}
    pp = brief.get("prompt_pack", {}) or {}
    neg = brief.get("negative_prompt", {}) or {}
    ot = brief.get("output_target", {}) or {}
    return {
        "brief_id": pm.get("brief_id"),
        "status": pm.get("status"),
        "operator_approval_token": pm.get("operator_approval_token"),
        "schema_version": pm.get("schema_version"),
        "primary_prompt_len": len(pp.get("primary_prompt") or ""),
        "aspect_ratio": pp.get("aspect_ratio"),
        "resolution_target_px": pp.get("resolution_target_px"),
        "brief_specific_negatives_count": len(neg.get("brief_specific_additions") or []),
        "output_path_requested_by_brief": ot.get("output_path"),
        "verification_checklist_count": len(brief.get("verification_checklist") or []),
        "chua_xac_nhan_count": len(brief.get("chua_xac_nhan_fields") or []),
    }


# -----------------------------------------------------------------------------
# Run folder
# -----------------------------------------------------------------------------

def allocate_run_folder(repo_root: Path, output_root_rel: str, brief_id: str) -> Tuple[Path, int]:
    """
    Build docs/automation/render_briefs/runs/<BRIEF_ID>/attempt_<NNN>/.
    NNN auto-increments to the first unused 3-digit number starting at 001.
    """
    base = repo_root / output_root_rel / (brief_id or "UNKNOWN_BRIEF_ID")
    base.mkdir(parents=True, exist_ok=True)
    n = 1
    while True:
        folder = base / f"attempt_{n:03d}"
        if not folder.exists():
            folder.mkdir(parents=True, exist_ok=False)
            return folder, n
        n += 1
        if n > 999:
            # Defensive: should never happen in practice
            raise RuntimeError("Exhausted attempt_NNN counter (>999) for brief_id=%s" % brief_id)


# -----------------------------------------------------------------------------
# FAL request shape (V0.1 — deliberately minimal)
# -----------------------------------------------------------------------------

def build_fal_request(
    compact_prompt: str,
    compact_negative: str,
    width: int,
    height: int,
    aspect_ratio: str,
    model_id: str,
    prompt_mode: str = "compact_prompt_v0_1",
) -> Dict[str, Any]:
    """
    FAL models differ in accepted keys; this shape covers the most common image-gen
    endpoints. Operator may need to adjust per model. prompt_mode is recorded as
    metadata only — FAL ignores the $-prefixed fields.
    """
    return {
        "$mikage_tool": f"{TOOL_NAME}/{TOOL_VERSION}",
        "$compact_prompt_mode": prompt_mode,
        "$intended_model_id": model_id,
        "prompt": compact_prompt,
        "negative_prompt": compact_negative,
        "image_size": {"width": width, "height": height},
        "aspect_ratio": aspect_ratio,
        "num_images": 1,
        "enable_safety_checker": True,
        "sync_mode": True,
    }


def call_fal(
    endpoint_url: str,
    api_key: str,
    payload: Dict[str, Any],
    timeout_seconds: int,
    user_agent: str,
) -> Tuple[bool, Optional[Dict[str, Any]], Optional[str]]:
    """
    Call FAL via stdlib urllib. Returns (ok, response_json_or_none, error_message_or_none).
    """
    body = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        endpoint_url,
        data=body,
        method="POST",
        headers={
            "Authorization": f"Key {api_key}",
            "Content-Type": "application/json",
            "Accept": "application/json",
            "User-Agent": user_agent,
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout_seconds) as resp:
            raw = resp.read().decode("utf-8", errors="replace")
            try:
                return True, json.loads(raw), None
            except json.JSONDecodeError as e:
                return False, {"raw": raw}, f"FAL returned non-JSON body: {e}"
    except urllib.error.HTTPError as e:
        raw = e.read().decode("utf-8", errors="replace") if hasattr(e, "read") else ""
        return False, {"http_status": e.code, "raw": raw}, f"HTTP {e.code} {e.reason}"
    except urllib.error.URLError as e:
        return False, None, f"URLError: {e.reason}"
    except Exception as e:  # pragma: no cover  (defensive)
        return False, None, f"Unhandled error: {type(e).__name__}: {e}"


def extract_image_url(response: Dict[str, Any]) -> Optional[str]:
    """
    Best-effort extraction of an image URL from a FAL response.
    Supports the common shapes:
       {"images": [{"url": "..."}]}, {"image": {"url": "..."}}, {"output": "..."}
    Returns None if no URL found.
    """
    if not isinstance(response, dict):
        return None
    imgs = response.get("images")
    if isinstance(imgs, list) and imgs:
        first = imgs[0]
        if isinstance(first, dict) and isinstance(first.get("url"), str):
            return first["url"]
        if isinstance(first, str):
            return first
    img = response.get("image")
    if isinstance(img, dict) and isinstance(img.get("url"), str):
        return img["url"]
    if isinstance(response.get("output"), str):
        return response["output"]
    return None


def download_image(url: str, dest: Path, timeout_seconds: int, user_agent: str) -> Tuple[bool, Optional[str]]:
    try:
        req = urllib.request.Request(url, headers={"User-Agent": user_agent})
        with urllib.request.urlopen(req, timeout=timeout_seconds) as resp:
            data = resp.read()
        dest.write_bytes(data)
        return True, None
    except Exception as e:
        return False, f"download failed: {type(e).__name__}: {e}"


# -----------------------------------------------------------------------------
# Report writers
# -----------------------------------------------------------------------------

def write_text(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def write_json(path: Path, data: Dict[str, Any]) -> None:
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def render_attempt_report_md(report: Dict[str, Any]) -> str:
    lines = [
        f"# RENDER ATTEMPT REPORT — {report.get('brief_id', 'UNKNOWN')} — attempt_{report.get('attempt_number', 1):03d}",
        "",
        f"Generated by: {TOOL_NAME}/{TOOL_VERSION}",
        f"Generated on: {report.get('generated_on')}",
        f"Status: **{report.get('status')}**",
        "",
        "## 1. INPUT",
        f"- source_brief_path: `{report.get('source_brief_path')}`",
        f"- source_brief_sha256_before: `{report.get('source_brief_sha256_before')}`",
        f"- source_brief_sha256_after:  `{report.get('source_brief_sha256_after')}`",
        f"- source_brief_unchanged: **{report.get('source_brief_unchanged')}**",
        "",
        "## 2. GATE OUTCOME",
        f"- operator_approval_token_present: **{report.get('operator_approval_token_present')}**",
        f"- provider: {report.get('provider')}",
        f"- model_id: `{report.get('model_id')}`",
        f"- fal_api_key_env_present: **{report.get('fal_api_key_env_present')}**",
        f"- dry_run: **{report.get('dry_run')}**",
        f"- api_called: **{report.get('api_called')}**",
        "",
        "## 3. PROMPT",
        f"- prompt_mode: `{report.get('prompt_mode')}`",
        f"- aspect_ratio: {report.get('aspect_ratio')}",
        f"- resolution_target_px (brief): {report.get('resolution_target_px')}",
        f"- resolved_width: {report.get('resolved_width')}",
        f"- resolved_height: {report.get('resolved_height')}",
        "",
        "## 4. OUTPUT",
        f"- output_path_requested_by_brief: `{report.get('output_path_requested_by_brief')}`",
        f"- actual_output_path: `{report.get('actual_output_path')}`",
        f"- fal_request_id: `{report.get('fal_request_id')}`",
        f"- cost_estimate: `{report.get('cost_estimate')}`",
        "",
        "## 5. SAFETY LATTICE",
        f"- verify_status: **{report.get('verify_status')}**",
        f"- anchor_established: **{report.get('anchor_established')}**",
        f"- canon_lock: **{report.get('canon_lock')}**",
        f"- asset_lock: **{report.get('asset_lock')}**",
        "",
        "## 6. NEXT_SAFE_TASK",
        "```text",
        report.get("next_safe_task", "(none)"),
        "```",
        "",
        "## 7. NOTES",
    ]
    for note in report.get("notes", []) or []:
        lines.append(f"- {note}")
    lines.append("")
    lines.append(f"*End of report. Status: {report.get('status')}.*")
    return "\n".join(lines) + "\n"


# -----------------------------------------------------------------------------
# Next-safe-task selection
# -----------------------------------------------------------------------------

def next_safe_task_for(status: str, brief_id: Optional[str]) -> str:
    bid = brief_id or "(brief_id missing)"
    if status == STATUS_BLOCKED_APPROVAL:
        return (
            f"OPERATOR_SET_APPROVAL_TOKEN_IN_BRIEF {bid} — issue "
            "OPERATOR_APPROVED=YES + APPROVAL_TOKEN in the brief JSON before retry."
        )
    if status == STATUS_MODEL_CHUA_XAC_NHAN:
        return (
            "OPERATOR_PICK_FAL_MODEL_ID — edit "
            "tools/render_gate/mikage_render_gate_config.json model_id to a concrete FAL model."
        )
    if status == STATUS_FAL_KEY_MISSING:
        return "OPERATOR_EXPORT_FAL_KEY_OR_FAL_API_KEY — set the env var before retry."
    if status == STATUS_DRY_RUN:
        return (
            f"OPERATOR_REVIEW_DRY_RUN_OUTPUTS for {bid}; if compact prompt + negative + "
            "fal_request.json look correct, re-run without --dry-run after also satisfying "
            "approval / model_id / FAL_KEY gates."
        )
    if status == STATUS_API_REQUEST_FAILED:
        return (
            "OPERATOR_INSPECT_FAL_RESPONSE — see fal_response.json in the attempt folder; "
            "retry only after diagnosing (auth / model / payload shape)."
        )
    if status == STATUS_RENDER_OK:
        return (
            f"COWORK_DRAFT_VERIFICATION_REPORT against brief verification_checklist for {bid}. "
            "Do NOT mark PASS, do NOT establish anchor, do NOT asset-lock — operator decides "
            "after Cowork drafts findings."
        )
    return "OPERATOR_REVIEW — unknown status."


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

def main(argv: Optional[list] = None) -> int:
    parser = argparse.ArgumentParser(
        prog=f"{TOOL_NAME}.py",
        description="Mikage render gate (FAL) V0.1 — hard-gated CLI for image render attempts.",
    )
    parser.add_argument(
        "--brief",
        required=True,
        help="Repo-relative or absolute path to a prompt_pack/v0.1 JSON brief sidecar.",
    )
    parser.add_argument(
        "--config",
        default=None,
        help="Path to render gate config JSON. Defaults to "
        "tools/render_gate/mikage_render_gate_config.json next to this script.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Never call FAL. Write reports and exit cleanly. Overrides all unlock gates.",
    )
    args = parser.parse_args(argv)

    notes: list = []

    # ------------------------------------------------------------------
    # Resolve paths
    # ------------------------------------------------------------------
    brief_path = Path(args.brief).resolve()
    if not brief_path.exists():
        sys.stderr.write(f"ERROR: brief not found: {brief_path}\n")
        return 2

    repo_root = _repo_root_from(brief_path)

    if args.config:
        config_path = Path(args.config).resolve()
    else:
        config_path = (repo_root / "tools" / "render_gate" / "mikage_render_gate_config.json").resolve()
    if not config_path.exists():
        sys.stderr.write(f"ERROR: config not found: {config_path}\n")
        return 2

    # ------------------------------------------------------------------
    # Load config + brief
    # ------------------------------------------------------------------
    try:
        cfg = load_config(config_path)
    except Exception as e:
        sys.stderr.write(f"ERROR: failed to parse config: {e}\n")
        return 2

    try:
        brief = load_brief(brief_path)
    except Exception as e:
        sys.stderr.write(f"ERROR: failed to parse brief JSON: {e}\n")
        return 2

    sha_before = _sha256_of_file(brief_path)

    fields = extract_brief_fields(brief)
    brief_id = fields["brief_id"] or "UNKNOWN_BRIEF_ID"
    schema_version = fields["schema_version"]
    if schema_version and schema_version != SCHEMA_EXPECTED:
        notes.append(
            f"schema_version='{schema_version}' does not match expected '{SCHEMA_EXPECTED}'. "
            "Tool proceeds but operator should reconcile."
        )

    # ------------------------------------------------------------------
    # Decide gate outcome
    # ------------------------------------------------------------------
    operator_token = fields["operator_approval_token"]
    operator_token_present = bool(operator_token)
    model_id = cfg.get("model_id", "CHUA_XAC_NHAN")
    fal_key = os.environ.get("FAL_KEY") or os.environ.get("FAL_API_KEY")
    fal_key_present = bool(fal_key)

    # Determine status. Order of precedence matters:
    # dry-run is a CLI override (operator-explicit "don't call").
    # Otherwise the safety gates trigger from strongest invariant first.
    if args.dry_run:
        status = STATUS_DRY_RUN
    elif not operator_token_present:
        status = STATUS_BLOCKED_APPROVAL
    elif model_id == "CHUA_XAC_NHAN":
        status = STATUS_MODEL_CHUA_XAC_NHAN
    elif not fal_key_present:
        status = STATUS_FAL_KEY_MISSING
    else:
        status = None  # will be set after API call

    # ------------------------------------------------------------------
    # Allocate run folder + write deterministic artifacts
    # ------------------------------------------------------------------
    try:
        run_folder, attempt_n = allocate_run_folder(
            repo_root=repo_root,
            output_root_rel=cfg.get("output_root", "docs/automation/render_briefs/runs"),
            brief_id=brief_id,
        )
    except Exception as e:
        sys.stderr.write(f"ERROR: failed to allocate run folder: {e}\n")
        return 2

    # Compact prompt + negative — routed by brief_id via select_compact_prompt().
    # V0.1 path preserved for legacy briefs; V0.2 brief_id routes to redesigned
    # front-loaded-positive compact prompt. Unknown brief_ids fall back to V0.1
    # and a note is recorded.
    compact_prompt, compact_negative, prompt_mode_label = select_compact_prompt(brief_id)
    known_brief_ids = {
        "BRIEF_COMMANDER_LYRE_PHASE_1_IMPERIAL_DUTY_V0_1",
        "BRIEF_COMMANDER_LYRE_PHASE_1_IMPERIAL_DUTY_V0_2",
    }
    if brief_id not in known_brief_ids:
        notes.append(
            f"brief_id '{brief_id}' is not a known compact-prompt routing target. "
            f"Falling back to V0.1 Lyre Phase 1 compact prompt. Add a new branch in "
            f"select_compact_prompt() for this brief in a future tool revision."
        )

    width, height = _aspect_ratio_to_size(
        aspect_ratio=fields["aspect_ratio"] or "2.35:1",
        resolution_target_px=fields["resolution_target_px"],
    )

    fal_request = build_fal_request(
        compact_prompt=compact_prompt,
        compact_negative=compact_negative,
        width=width,
        height=height,
        aspect_ratio=fields["aspect_ratio"] or "2.35:1",
        model_id=model_id,
        prompt_mode=prompt_mode_label,
    )

    write_text(run_folder / "prompt_compact.txt", compact_prompt + "\n")
    write_text(run_folder / "negative_compact.txt", compact_negative + "\n")
    write_json(run_folder / "fal_request.json", fal_request)

    # ------------------------------------------------------------------
    # Maybe call FAL
    # ------------------------------------------------------------------
    api_called = False
    fal_response: Optional[Dict[str, Any]] = None
    fal_request_id: Optional[str] = None
    actual_output_path: Optional[str] = None
    cost_estimate = "CHUA_XAC_NHAN"

    if status is None:
        # All gates open; perform the API call.
        endpoint_url = cfg.get("fal_endpoint_template", "https://fal.run/{model_id}").format(
            model_id=model_id
        )
        ok, resp, err = call_fal(
            endpoint_url=endpoint_url,
            api_key=fal_key or "",
            payload=fal_request,
            timeout_seconds=int(cfg.get("fal_timeout_seconds", 120)),
            user_agent=cfg.get("fal_request_user_agent", f"{TOOL_NAME}/{TOOL_VERSION}"),
        )
        api_called = True
        fal_response = resp or {}
        if not ok:
            status = STATUS_API_REQUEST_FAILED
            notes.append(f"FAL API call failed: {err}")
            write_json(run_folder / "fal_response.json", fal_response)
        else:
            write_json(run_folder / "fal_response.json", fal_response)
            fal_request_id = fal_response.get("request_id") or fal_response.get("id")
            if isinstance(fal_response.get("cost"), (int, float)):
                cost_estimate = str(fal_response.get("cost"))
            image_url = extract_image_url(fal_response)
            if image_url:
                out_path = run_folder / "output.png"
                ok_dl, err_dl = download_image(
                    image_url, out_path,
                    timeout_seconds=int(cfg.get("fal_timeout_seconds", 120)),
                    user_agent=cfg.get("fal_request_user_agent", f"{TOOL_NAME}/{TOOL_VERSION}"),
                )
                if ok_dl:
                    actual_output_path = str(out_path.relative_to(repo_root))
                    status = STATUS_RENDER_OK
                    notes.append(
                        "Output saved to run folder. NOT copied to brief output_target.output_path; "
                        "operator promotes the image only after verification report."
                    )
                else:
                    status = STATUS_API_REQUEST_FAILED
                    notes.append(f"Image download failed: {err_dl}")
            else:
                status = STATUS_API_REQUEST_FAILED
                notes.append(
                    "FAL response did not contain an image URL in any recognized shape. "
                    "See fal_response.json."
                )
    else:
        # Gated path: do not call API, do not write fal_response.json.
        if status == STATUS_BLOCKED_APPROVAL:
            notes.append(
                "operator_approval_token is null in the brief. "
                "Tool refused to call FAL. No API request was sent."
            )
        elif status == STATUS_MODEL_CHUA_XAC_NHAN:
            notes.append(
                "config.model_id is 'CHUA_XAC_NHAN' (V0.1 default safety stop). "
                "Tool refused to call FAL. No API request was sent."
            )
        elif status == STATUS_FAL_KEY_MISSING:
            notes.append(
                "Neither FAL_KEY nor FAL_API_KEY env var is set. "
                "Tool refused to call FAL. No API request was sent."
            )
        elif status == STATUS_DRY_RUN:
            notes.append(
                "--dry-run set. Tool wrote compact prompt + negative + fal_request.json "
                "and exited without contacting FAL."
            )

    # ------------------------------------------------------------------
    # Confirm source brief unchanged
    # ------------------------------------------------------------------
    sha_after = _sha256_of_file(brief_path)
    source_brief_unchanged = sha_after == sha_before
    if not source_brief_unchanged:
        notes.append(
            "WARNING: source brief sha256 changed during run. This tool MUST NOT modify "
            "the brief; investigate immediately."
        )

    # ------------------------------------------------------------------
    # Compose report
    # ------------------------------------------------------------------
    report = {
        "brief_id": brief_id,
        "source_brief_path": str(brief_path.relative_to(repo_root)) if brief_path.is_relative_to(repo_root) else str(brief_path),
        "source_brief_sha256_before": sha_before,
        "source_brief_sha256_after": sha_after,
        "source_brief_unchanged": source_brief_unchanged,
        "status": status,
        "provider": cfg.get("provider", "fal"),
        "model_id": model_id,
        "operator_approval_token_present": operator_token_present,
        "fal_api_key_env_present": fal_key_present,
        "dry_run": bool(args.dry_run),
        "api_called": api_called,
        "prompt_mode": prompt_mode_label,
        "aspect_ratio": fields["aspect_ratio"],
        "resolution_target_px": fields["resolution_target_px"],
        "resolved_width": width,
        "resolved_height": height,
        "output_path_requested_by_brief": fields["output_path_requested_by_brief"],
        "actual_output_path": actual_output_path,
        "fal_request_id": fal_request_id,
        "cost_estimate": cost_estimate,
        "verify_status": "NOT_STARTED",
        "anchor_established": "NO",
        "canon_lock": "NO",
        "asset_lock": "NO",
        "attempt_number": attempt_n,
        "run_folder": str(run_folder.relative_to(repo_root)) if run_folder.is_relative_to(repo_root) else str(run_folder),
        "tool": f"{TOOL_NAME}/{TOOL_VERSION}",
        "generated_on": _now_iso(),
        "next_safe_task": next_safe_task_for(status, brief_id),
        "notes": notes,
    }

    write_json(run_folder / "render_attempt_report.json", report)
    write_text(run_folder / "render_attempt_report.md", render_attempt_report_md(report))

    # ------------------------------------------------------------------
    # Print machine-readable summary to stdout
    # ------------------------------------------------------------------
    print(json.dumps({
        "STATUS": status,
        "BRIEF_ID": brief_id,
        "ATTEMPT": attempt_n,
        "API_CALLED": api_called,
        "DRY_RUN": bool(args.dry_run),
        "RUN_FOLDER": report["run_folder"],
        "SOURCE_BRIEF_UNCHANGED": source_brief_unchanged,
        "NEXT_SAFE_TASK": report["next_safe_task"],
    }, indent=2))

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except SystemExit:
        raise
    except Exception:
        sys.stderr.write("UNHANDLED ERROR — see traceback below.\n")
        traceback.print_exc()
        sys.exit(2)
